version: 0.2

env:
  variables:
    APP_VERSION: "1.0.0"

phases:
  install:
    runtime-versions:
        nodejs: 10

    commands:
      - npm install

  build:
    commands:
      - npm run clean
      - npm run dev --ver=$APP_VERSION
      - npm run prod --ver=$APP_VERSION
      - echo Finalizou OK

artifacts:
  discard-paths: yes
  base-directory: dist/
  name: css/$APP_VERSION
  files:
    - rhino.css
    - rhino.min.css