version: 0.2

env:
  variables:
    APP_VERSION: "1.3.0"

phases:
  install:
    runtime-versions:
        nodejs: 10

    commands:
      - npm install

  build:
    commands:
      - npm run clean
      - ./node_modules/.bin/lessc index.less dist/rhino-$APP_VERSION.css
      - ./node_modules/.bin/lessc index.less dist/rhino-$APP_VERSION.min.css --clean-css
      - echo Finalizou OK

artifacts:
  discard-paths: yes
  base-directory: dist/
  name: css
  files:
    - rhino-$APP_VERSION.css
    - rhino-$APP_VERSION.min.css
