version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10

    commands:
      - cd $CODEBUILD_SRC_DIR
      - npm install

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - npm run build
      - echo Finalizou OK

artifacts:
  files:
    - rhino.css
    - rhino.min.css
  discard-paths: yes
  base-directory: dist/