version: 0.2

env:
  APP_VERSION: "1.0.0"

phases:
  install:
    runtime-versions:
        nodejs: 10

    commands:
      - cd $CODEBUILD_SRC_DIR
      - npm install

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - npm run clean
      - npm run dev --ver=$APP_VERSION
      - npm run prod --ver=$APP_VERSION
      - echo Finalizou OK

artifacts:
  files:
    - rhino-$APP_VERSION.css
    - rhino-$APP_VERSION.min.css
  discard-paths: yes
  base-directory: dist/