version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10

  build:
    commands:
        - cd $CODEBUILD_SRC_DIR
        - npm install
        - npm run build
        - echo Finalizou OK

  artifacts:
    files:
      - dist/rhino.css
      - dist/rhino.min.css