version: 0.2

env:
  variables:
    APP_VERSION: "1.6.0"

phases:
  install:
    runtime-versions:
        nodejs: 10

    commands:
      - npm install

  build:
    commands:
      # Compilar versao
      - npm run clean
      - ./node_modules/.bin/lessc index.less dist/rhino-$APP_VERSION.css --no-comments
      - ./node_modules/.bin/lessc index.less dist/rhino-$APP_VERSION.min.css --clean-css
      - ./node_modules/.bin/lessc no-conflict.less dist/rhino-noconflict-$APP_VERSION.css --no-comments
      - ./node_modules/.bin/lessc no-conflict.less dist/rhino-noconflict-$APP_VERSION.min.css --clean-css

      # Atualizar repositorio de assets
      - git clone https://$GITHUB_TOKEN@github.com/rhino-org/assets.git _assets
      - cd ./_assets/css/
      
      # Copiar arquivos compilados para a pasta css
      - cp -frvp $CODEBUILD_SRC_DIR/dist/rhino-$APP_VERSION.css ./
      - cp -frvp $CODEBUILD_SRC_DIR/dist/rhino-$APP_VERSION.min.css ./
      - cp -frvp $CODEBUILD_SRC_DIR/dist/rhino-noconflict-$APP_VERSION.css ./
      - cp -frvp $CODEBUILD_SRC_DIR/dist/rhino-noconflict-$APP_VERSION.min.css ./      
      - cd ../
      
      # Fazer um novo commit agora com a nova documentação de /dev
      - git config --global user.email "bugotech@gmail.com"
      - git config --global user.name "RhinoOrg"
      - git add .
      - git commit -m "atualizando assets CSS"
      - git push origin main -f

      - echo Finalizou OK
