version: 0.2

env:
  variables:
    APP_VERSION: "1.0.0"

phases:
  install:
    runtime-versions:
        nodejs: 10

    commands:
      - npm install

  build:
    commands:
      - npm run clean
      - npm run dev --app=$APP_VERSION
      - npm run prod --app=$APP_VERSION
      - echo Finalizou OK

artifacts:
  discard-paths: yes
  base-directory: dist/
  name: css
  files:
    - rhino-$APP_VERSION.css
    - rhino-$APP_VERSION.min.css